### ISSUE TITLE
contributor

### ISSUE THREAD

**Issue by sylvain-combe-sonarsource** [daniel-meppiel-sonarsource/sonarqube-latest-k8s#1]
Hello @daniel-meppiel-sonarsource ,
can you make me a contributor to your project here? I would submit a PR for the upgrade to networking v1.
Thanks
Sylvain

**Comment by daniel-meppiel-sonarsource** [comment]
Hi @sylvain-combe-sonarsource , 

I can make you a contributor, good idea to update since v1 was released on v1.19+ which is now the oldest Kubernetes version under official support.
